# Generated by Django 3.2.8 on 2021-12-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('wishlist', '0002_auto_20211208_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(through='wishlist.WishlistItem', to='products.Product'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
